//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visitante.Model
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class VisitanteEntities : DbContext
    {

        public VisitanteEntities(string connection): base(connection)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Instalacion> Instalacion { get; set; }
        public virtual DbSet<RegistroVisitante> RegistroVisitante { get; set; }
        public virtual DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public virtual DbSet<Visitante> Visitante { get; set; }
    }
}
